### ISSUE TITLE
Add Details page for viewing details of an Issued Credential

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/ssi-console#9]
Add a more detailed Details view for the Issued Credentials to see all data and metadata associated with an Issued Credential, including Credential Status List.

This issue can also address adding any expiry related info to the panel view of the Credential.

**Comment by michaelneale** [comment]
Would it make sense to have any code snippets/curl/examples on how you would use the credential (or links to docs?) - that may not make sense but just thinking aloud

**Comment by kirahsapong** [comment]
> Would it make sense to have any code snippets/curl/examples on how you would use the credential (or links to docs?) - that may not make sense but just thinking aloud

This is a good idea. So far looks like this below: 

<img width="1725" alt="Screenshot 2023-06-15 at 4 52 50 AM" src="https://github.com/TBD54566975/ssi-console/assets/102400653/7abec3eb-96bd-4867-a11d-5360538d8276">

Going to open a new issue to track this
