### ISSUE TITLE
invalid create credential request: json: unknown field "issuerKid"

### ISSUE THREAD

**Issue by grahnj** [TBD54566975/ssi-console#92]
The `issuerKid` field contained in the `credentialPayload` object during `handleSubmit` causes a 400 exception during `handleRequest`. This appears to resolve by renaming the field to `verificationMethodId`.

This issue occurs in at least two of the workflow Modal.tsx files:

- CredentialManifests
- IssuerCredentials

**Comment by kirahsapong** [comment]
Thanks for identifying and fixing! Well done 🎉
